site_name: "openHASP"
site_description: "Open firmware for MCUs to drive a low-cost commodity touch display"
site_author: "Francis Van Roie"

copyright: Copyright &copy; 2020 - 2021 Francis Van Roie and contributors

repo_url: https://github.com/HASwitchPlate/openHASP
repo_name: HASwitchPlate/openHASP
edit_uri: https://github.com/fvanroie/new-docs/edit/0.6/docs/

theme:
  logo: "assets/images/logo.png"
  favicon: favicon.ico
  icon:
    repo: fontawesome/brands/github
  name: material
  custom_dir: custom_theme
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Light mode
  features:
    - navigation.instant
    - navigation.tracking
#    - navigation.tabs
#    - navigation.tabs.sticky
#    - navigation.sections
#    - navigation.expand
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - toc:
      permalink: "~"
      toc_depth: 3

extra:
  version: v0.6.0 beta

  generator: false

  # alternate:
  #   - name: Default (en)
  #     link: ./
  #     lang: en

  #   # Switch to English
  #   - name: English
  #     link: ./en/
  #     lang: en

  #   # Switch to Dutch
  #   - name: Nederlands
  #     link: ./nl/
  #     lang: nl

  social:
    - icon: material/github
      link: https://github.com/HASwitchPlate/openHASP/discussions
      name: GitHub Discussions
    - icon: material/discord
      link: https://discord.gg/VCWyuhF
      name: Discord Chat
    - icon: material/home-assistant
      link: https://community.home-assistant.io/t/openhasp-an-mqtt-driven-touchscreen-scene-controller/300853
      name: Home Assistant Forum

  version:
    provider: mike
    default: 0.5


# nav:
#   - Integrations:
#       - Home Assistant:
#           - How-To: custom-component/howto.md
#           - Example configurations: custom-component/sampl_conf.md
#           - Example automations: custom-component/sampl_autom.md
#       - openHAB:
#           - Installation and Example: integration_openhab.md
#       - Other examples:
#           - Page navigation: example-pagination.md
#           - Dash UI: example-dashui.md
#           - Widgets Demo: example-widgets.md
#           - Lovelace Entities: example-lovelace.md

# nav:
#   - Home: index.md
#   - Getting Started: getting-started.md
#   - Installation:
#     - ESP32: installation/ESP32.md
#     - ESP8266: installation/ESP8266.md
#     - Wifi Setup: installation/wifi-setup.md
#     - Firmware Upgrade: installation/firmware-update.md
#   - Design:
#     - Pages: pages.md
#     - Objects: objects.md
#     - Styling: styling.md
#     - Fonts: fonts.md
#     - Commands: commands.md
#   - Hardware:
#       - Devices:
#           - ESP32-Touchdown: devices/esp32-touchdown.md
#           - devices/freetouchdeck.md
#           - Lanbon L8: devices/lanbon-l8.md
#           - M5Stack core2: devices/m5stack-core2.md
#           - Wireless-Tag: devices/wt32-sc01.md
#       - Displays:
#           - displays/ILI9341_IPS.md
#           - displays/MHS4001.md
#           - displays/MRB3511.md
#           - displays/MSPxxxx.md
#           - displays/Waveshare_RPi_LCD_Rev_C.md
#   - Gallery: gallery.md
#   - FAQ: faq.md
#   - Compiling: compiling.md
#   - License: license.md
#   - ...

plugins:
  - search
  - git-revision-date
  - awesome-pages:
      strict: false
  - table-reader
  # - i18n:
  #     default_language: en
  #     languages:
  #       en: English
  #       nl: Nederlands
  #     nav_translations:
  #       nl:
  #         Home: Thuis
  #         Design: Ontwerp
  #         Pages: Pagina's
  #         Objects: Objecten
  #         Styling: Stijleigenschappen
  #         Fonts: Lettertypen
  #         Commands: Commando's