site_name: "openHASP"
site_description: "Open firmware for MCUs to drive a low-cost commodity touch display"
site_author: "Francis Van Roie"

repo_url: https://github.com/HASwitchPlate/openHASP
edit_uri: https://github.com/HASwitchPlate/openHASP-docs/tree/master/docs

theme:
  name: windmill
  custom_dir: custom_theme

strict: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Installation:
      - ESP32 Installation: ESP32.md
      - ESP8266 Installation: ESP8266.md
      - Wi-Fi Setup: wifi-setup.md
  - Configuration:
      - configuration/http.md
      - configuration/wifi.md
      - configuration/mqtt.md
      - configuration/hasp.md
      - configuration/display.md
      - configuration/gpio.md
      - configuration/debug.md
  - Design:
      - pages.md
      - objects.md
      - fonts.md
      - styling.md
  - Integrations:
      - Home Assistant:
          - How-To: custom-component/howto.md
          - Example configurations: custom-component/sampl_conf.md
          - Example automations: custom-component/sampl_autom.md
      - openHAB:
          - Installation and Example: integration_openhab.md
      - Other examples:
          - Page navigation: example-pagination.md
          - Dash UI: example-dashui.md
          - Widgets Demo: example-widgets.md
          - Lovelace Entities: example-lovelace.md
  - commands.md
  - FAQ: faq.md
  - firmware-update.md
  - gallery.md
  - Devices:
      - Adafruit Featherwing: devices/featherwing.md
      - ESP32 TouchDown: devices/esp32-touchdown.md
      - devices/freetouchdeck.md
      - Lanbon L8: devices/lanbon-l8.md
      - M5Stack core2: devices/m5stack-core2.md
      - Wireless-Tag: devices/wt32-sc01.md
  - Displays:
      - displays/ILI9341_IPS.md
      - displays/MHS4001.md
      - displays/MRB3511.md
      - displays/MSPxxxx.md
      - displays/Waveshare_RPi_LCD_Rev_C.md
  - Compiling:
      - compiling-locally.md
      - compiling-gitpod.md
      - compiling-customize.md
      - block-diagram-tests.md
  - license.md

markdown_extensions:
  - toc:
      permalink: "~"
      toc_depth: 2
  - admonition
  - pymdownx.emoji
  - attr_list

extra:
  history_buttons: false
  version: v0.5.2
  logo: "assets/images/logo.png"

plugins:
  - search
  - table-reader
