site_name: openHASP Docs
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

plugins:
  - search

extra:
  alternate:

    # Switch to English
    - name: English
      link: <your-site>/en/
      lang: en

    # Switch to Dutch
    - name: Nederlands
      link: <your-site>/de/
      lang: de


  version:
    provider: mike
